version: '3'
services:
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube
    restart: unless-stopped
    ports:
      - '8081:8081'
      - '443:443'
    volumes:
      - ./deploy/docker/volumes/metube/downloads:/downloads
    networks:
      - default

networks:
  default:
